name: CI/CD Piepeline

on:
    push:
        branches: ["main"]
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Upgrade pip & install
              run: |
                pip install --upgrade pip setuptools wheel
                pip install .[dev]

            - name: Run tests
              run: pytest

    build-and-deploy:
        runs-on: ubuntu-latest
        needs: test # only run if tests pass
        if: github.ref == 'refs/heads/main'

        steps:
            - uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: login to Amazon ECR
              id: ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build, tag, and push image to Amazon ECR
              run: |
                IMAGE_REPO = ${{steps.ecr.outputs.registry}}/wb-top-traveling-analysis
                IMAGE_TAG = latest
                docker build -t $IMAGE_REPO:$IMAGE_TAG .
                docker push $IMAGE_REPO:$IMAGE_TAG